### PR TITLE
Added colors

### PR DESCRIPTION
**Pull request by Kerrigan29a**

### CODE REVIEW

**Comment by LonnyGomes** [comment]
Very cool! Thanks @Kerrigan29a, I'm excited to incorporate this! Would it be possible to perhaps squash the commit for the `Added Travis support` and to maybe break out build script updates and code changes you added as two separate commits? It just may be easier to see all the work you did! Thanks for the contribution, I'll try testing this later today!

**Comment by Kerrigan29a** [comment]
I made the pull request before adding the Travis Support, I don't know why it was also added. If you erase the .travis.yml file and restore the 2 readme files the Travis support will be disabled.

**Comment by Kerrigan29a** [comment]
I've never manager a pull request in my repos, so I don't know about it. Can you select by hand which commits use in the merge of this pull request?

**Comment by stevenhoneyman** [comment]
I look forward to testing this out, thanks!

No, you can't pick-and-choose which commits to use. Any commits you add to your master branch will get added to this pull request. What is supposed to happen is you create a new branch e.g. "colorsupport" with only changes affecting this feature addition, and submit the request for that branch. Anything else you change in another branch or master will not be added in that case.

**Comment by Kerrigan29a** [comment]
ok, I'll do that

**Comment by Kerrigan29a** [comment]
Added new request #17

**Comment by LonnyGomes** [comment]
The merge was implemented with PR #17 so I'm closing this one out.

**Pull request closed without merging**
